language: node_js
node_js:
  - 12

deploy:
  provider: heroku
  api_key:
    secure: jC+GTBcNhF1cOh7p3Bjm3qtlAhrGBYdsTaw+4xSg8jDxz7tuaK08qE30g5f0FFNwnNK3VjBDzezmlPEFncHo3klcj/KdjQBe9kD1HeCxKXVPy3Vr5Z5epRBjWj2IDpiRZrsZUO+TxoopYdcUndZTHuazg9NvRh6BAdO2OeSAp8dKAQ3QF1yMIwzrl4dnZAAhO4iU4kOj+8eO5kMRzPIZ+FaKPW2TNmcR2TBHFmsGkkDnhvZrzWQK6GVP6XwiS+c1XRTiU+LNMW/XoyUbTEKbAklXtB/7PKpxykPFqbmSCMse18CKnMJtdrW1psY92sAgOdsauXLBOWxT/WB6E2cSm41SJyIzgNDEuzF9+Q0h8m8kyBpmlJE8krOOhYUJofy+VdMv/XErjaalQJYRa66KPh/nCvqaFFeyRdowbgXepr3xYGqg/5yQtZBtTrylv/zZbTS07FU1WrxgwpQu/jtGhM9BrgTQ2GzlvqwTP9nPALFTMekLD4IWjRDULJzPq5dZLA6fJpuQzKakUMjG+Tg8tTkDDbcheRtnP7BKIwIT+F6wf4jgIF3Iq6lNr3G6wfQLzrmpKV9hxSMKwdrqPLO5tO08jEauPqCWzsn3w6bpBwP2DjgJH0lXYyEiQw3menDCRW8X2GdmZA0hZRbsoLnQnHfDP1xfePe576oQJwgx3yA=
  app: phufbq-skeleton-nodejs-app